In [1]:
import re
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
from main import MainFunc


mf = MainFunc()

In [12]:
dfd = pd.read_csv('data/d.csv')# dfd dataframe dirty, lets clean it 
dfd = dfd.iloc[:,[1,2,3,5]] # filter only colums we need
dfd = dfd[dfd['Amount'] < 0] # filter amount by expenses ex. -10
dfd = dfd.rename(columns = {'Post Date':'Date'})
dfd['Date'] = pd.to_datetime(dfd['Date']) # convert to datetime datatye
dfd['Amount'] = dfd['Amount'].abs() # convert -10 to + 10

In [14]:
df=dfd.copy()

cond1 = df['Category'] == 'Food & Drink'
cond2 = df['Amount']  > 200 

df.loc[cond1 & cond2]

          Date            Description           Category  Amount
0   2020-08-07  Prime Video*MF31C1PQ0           Shopping    7.41
1   2020-08-06      TST* MEXICUE - DC       Food & Drink  140.26
2   2020-08-05    CVS/PHARMACY #02817  Health & Wellness    8.79
3   2020-08-05       WALGREENS #15360  Health & Wellness   18.72
4   2020-08-05        STARRY INTERNET  Bills & Utilities   50.00
..         ...                    ...                ...     ...
628 2020-01-03            UBER   TRIP             Travel    8.00
629 2020-01-03            WALMART.COM           Shopping   52.50
630 2020-01-02         7-ELEVEN 33452                Gas    6.20
631 2020-01-02            UBER   TRIP             Travel   13.09
632 2020-01-01   SMITHSONIANBUSVENT I  Gifts & Donations   35.00

[612 rows x 4 columns]

data cleaning functions

In [4]:
dfc=dfd# dfc dataframe clean
dfc['Description'] = dfc['Description'].map(mf.clean_desc)
dfc['Category'] = dfc['Category'].map(mf.clean_cats) 
dfc['Month'] = dfc['Date'].map(lambda x : str(x.month) +'.'+ str(x.strftime("%B")))

wrangle data

In [5]:
#dfd=dfd[(dfd['Date'] >= '2020-07-01') & (dfd['Date'] < '2020-08-01')] 
#dfd.groupby(['Month', 'Category']).sum().head(50) 
g=dfd.groupby(['Month', 'Category']).agg(['sum', 'count'])
g=pd.DataFrame(g)
g.head(500)

                                                                    Description  \
                                                                            sum
Month      Category
1.January  Bills & Utilities  AMZ_Sling_TV_L__L__CAudiblePYL_Tilton_Bernstei...
           Entertainment                            HBOREGAL_CINEMAS_MOBILE_APP
           Food & Drink       CHIPOTLEHBOPHILZ_COFFEECENTRAL_LIQUORSCARMINE_...
           Groceries          YESTRADERINSTACARTGIANTSAFEWAYTRADERWHOLEFDSTR...
           MISC                                      ELEVENSMITHSONIANBUSVENT_I
           Personal           CVSCVSWEDDING_EXPERIENCEBANGSALONVERIZONCENTER...
           Shopping           AMZNWALMART_COMAPPLE_COM_BILLPrimeT_J_MAXXPrim...
           Travel             LYFTLYFTLYFTLYFTLYFTLYFTGAL_PLC_CHNTN_ELYFTLYF...
2.February Bills & Utilities  AMZ_Sling_TV_L__L__CAudiblePrimeSTARRY_INTERNE...
           Entertainment                                                    HBO
           Food & Drink       MOMIJI_RESTAURANTDAIKAYABLUESTONE_LANE_____TH_...
           Groceries          TRADERWHOLEFDSYESTRADERSAFEWAYSAFEWAYYESTRADER...
           Personal           CVSCVSWALGREENSBED_BATH____BEYONDBANGSALONVERI...
           Shopping           APPLE_COM_BILLPrimePrimeAmazonT_J_MAXXMARSHALL...
           Travel             LYFTLYFTLYFTLYFTLYFTHOTELSCOMLYFTLYFTUBERLYFTL...
3.March    Bills & Utilities  AMZ_Sling_TV_L__L__CAudibleSTARRY_INTERNETPYL_...
           Entertainment                                                    HBO
           Food & Drink       WASHINGTON_WINE____LIQUORCENTRAL_LIQUORSWASHIN...
           Groceries          YESTRADERSAFEWAYSAFEWAYGIANTINSTACARTWHOLEFDSI...
           Personal           AMZ_Fabric_comWALGREENSMEDICAL_FACULTY_ASSOCIA...
           Shopping           PrimeAPPLE_COM_BILLAMZNAMZNWALMART_COMPrimeAMZ...
           Travel             LYFTLYFTLYFTLYFTLYFTLYFTMETRO_____METRO_CENTER...
4.April    Bills & Utilities  DNH_GODADDY_COMAMZ_Sling_TV_L__L__CDNH_GODADDY...
           Entertainment                                                    HBO
           Food & Drink       JALEO_DCMARC_GLOSSERMANCENTRAL_LIQUORSEYE_STRE...
           Groceries          SAFEWAYYESTRADERINSTACARTAMZ_Swanson_Health_PS...
           Shopping           AmazonAmazonAPPLE_COM_BILLAmazonPrimeCONTES_BI...
           Travel                                    ZipcarZIPCAR_INCZIPCAR_INC
5.May      Bills & Utilities  AMZ_Sling_TV_L__L__CAMZ_Sling_TV_L__L__CAudibl...
           Entertainment                                HBOAMZ_The_Washington_P
           Food & Drink       CENTRAL_LIQUORSCENTRAL_LIQUORSCENTROLINACENTRO...
           Groceries          GW_DELICATESSENINSTACARTWHOLEFDSCAPT_WHITES_SE...
           MISC                                                          ELEVEN
           Personal                               CVSCVSWALGREENSAMZ_Fabric_com
           Shopping           AMZNAMZNAMZNAPPLE_COM_BILLAmazonIMPERIAL_WINE_...
6.June     Bills & Utilities  Yes_EnergyAMZ_Sling_TV_L__L__CAudibleSTARRY_IN...
           Entertainment                                HBOAMZ_The_Washington_P
           Food & Drink       LE_DIPLOMATEEYE_STREET_CELLARSJALEO_DCSUBWAYST...
           Groceries          SAFEWAYCAPT_WHITES_SEAFOOD_CITYWHOLEFDSWHOLEFD...
           MISC                                       PP_FACEBOOKPAY_AMERICANCA
           Personal                                   CVSBANGSALONVERIZONCENTER
           Shopping           AmazonAmazonAMZNAMZNAPPLE_COM_BILLAMZNAMZNSODA...
           Travel                                                        Zipcar
7.July     Bills & Utilities  AMZ_Sling_TV_L__L__CYes_EnergyAMZ_Sling_TV_L__...
           Education                                                 CODECADEMY
           Entertainment                                                    HBO
           Food & Drink       SOMTAM_HOLDINGS___LLCSTARBUCKSPENN_QUARTER_SPO...
           Groceries          HANA_GROCERY_STORETRADERINSTACARTWHOLEFDSSAFEW...
           MISC                                                          ELEVEN
           Personal                           WALGREENSWALGREENSCVSCVSWALGREENS
           Shopping           AMZNAmazonDISTRICT_CUTLERYAPPLE_COM_BILLPrimeA...
8.August   Bills & Utilities  STARRY_INTERNETPYL_Tilton_Bernstein_ManaEtsyTM...
           Food & Drink       MEXICUE___DCEYE_STREET_CELLARSFREE_STATEIN__TH...
           Groceries                SAFEWAYTRADERHANA_GROCERY_STOREGIANTSAFEWAY
           Personal                                  CVSWALGREENSLOGAN_HARDWARE
           Shopping                                                       Prime

                                     Amount
                             count      sum count
Month      Category
1.January  Bills & Utilities     3   570.50     3
           Entertainment         2    42.15     2
           Food & Drink         23  1320.14    23
           Groceries            19  1052.74    19
           MISC                  2    41.20     2
           Personal              6    95.23     6
           Shopping             14   581.33    14
           Travel               24   468.35    24
2.February Bills & Utilities     5   752.15     5
           Entertainment         1    15.89     1
           Food & Drink         12   597.31    12
           Groceries            20   931.57    20
           Personal              5    74.74     5
           Shopping             31  1373.97    31
           Travel               23   799.31    23
3.March    Bills & Utilities     7   837.79     7
           Entertainment         1    15.89     1
           Food & Drink         16   985.51    16
           Groceries            33  1770.85    33
           Personal              7   163.61     7
           Shopping             19   748.71    19
           Travel                9   137.96     9
4.April    Bills & Utilities     7   950.47     7
           Entertainment         1    15.89     1
           Food & Drink          8   244.60     8
           Groceries            28  1924.88    28
           Shopping             25   466.13    25
           Travel                3   135.32     3
5.May      Bills & Utilities     7  1156.41     7
           Entertainment         2    16.95     2
           Food & Drink         23   929.19    23
           Groceries            19  1318.82    19
           MISC                  1     2.99     1
           Personal              4   166.22     4
           Shopping             27   638.04    27
6.June     Bills & Utilities     7   835.67     7
           Entertainment         2    26.49     2
           Food & Drink         16  1349.98    16
           Groceries            20  1489.25    20
           MISC                  1    31.12     1
           Personal              2   120.23     2
           Shopping             37   912.26    37
           Travel                1    35.28     1
7.July     Bills & Utilities     9   829.11     9
           Education             1   239.88     1
           Entertainment         1    15.89     1
           Food & Drink         19  1173.45    19
           Groceries            17  1440.13    17
           MISC                  1    10.50     1
           Personal              5    60.36     5
           Shopping             18   528.39    18
8.August   Bills & Utilities     4   669.13     4
           Food & Drink          5   326.27     5
           Groceries             5   220.55     5
           Personal              3    79.15     3
           Shopping              1     7.41     1

In [6]:
g.head(151)

                                                                    Description  \
                                                                            sum
Month      Category
1.January  Bills & Utilities  AMZ_Sling_TV_L__L__CAudiblePYL_Tilton_Bernstei...
           Entertainment                            HBOREGAL_CINEMAS_MOBILE_APP
           Food & Drink       CHIPOTLEHBOPHILZ_COFFEECENTRAL_LIQUORSCARMINE_...
           Groceries          YESTRADERINSTACARTGIANTSAFEWAYTRADERWHOLEFDSTR...
           MISC                                      ELEVENSMITHSONIANBUSVENT_I
           Personal           CVSCVSWEDDING_EXPERIENCEBANGSALONVERIZONCENTER...
           Shopping           AMZNWALMART_COMAPPLE_COM_BILLPrimeT_J_MAXXPrim...
           Travel             LYFTLYFTLYFTLYFTLYFTLYFTGAL_PLC_CHNTN_ELYFTLYF...
2.February Bills & Utilities  AMZ_Sling_TV_L__L__CAudiblePrimeSTARRY_INTERNE...
           Entertainment                                                    HBO
           Food & Drink       MOMIJI_RESTAURANTDAIKAYABLUESTONE_LANE_____TH_...
           Groceries          TRADERWHOLEFDSYESTRADERSAFEWAYSAFEWAYYESTRADER...
           Personal           CVSCVSWALGREENSBED_BATH____BEYONDBANGSALONVERI...
           Shopping           APPLE_COM_BILLPrimePrimeAmazonT_J_MAXXMARSHALL...
           Travel             LYFTLYFTLYFTLYFTLYFTHOTELSCOMLYFTLYFTUBERLYFTL...
3.March    Bills & Utilities  AMZ_Sling_TV_L__L__CAudibleSTARRY_INTERNETPYL_...
           Entertainment                                                    HBO
           Food & Drink       WASHINGTON_WINE____LIQUORCENTRAL_LIQUORSWASHIN...
           Groceries          YESTRADERSAFEWAYSAFEWAYGIANTINSTACARTWHOLEFDSI...
           Personal           AMZ_Fabric_comWALGREENSMEDICAL_FACULTY_ASSOCIA...
           Shopping           PrimeAPPLE_COM_BILLAMZNAMZNWALMART_COMPrimeAMZ...
           Travel             LYFTLYFTLYFTLYFTLYFTLYFTMETRO_____METRO_CENTER...
4.April    Bills & Utilities  DNH_GODADDY_COMAMZ_Sling_TV_L__L__CDNH_GODADDY...
           Entertainment                                                    HBO
           Food & Drink       JALEO_DCMARC_GLOSSERMANCENTRAL_LIQUORSEYE_STRE...
           Groceries          SAFEWAYYESTRADERINSTACARTAMZ_Swanson_Health_PS...
           Shopping           AmazonAmazonAPPLE_COM_BILLAmazonPrimeCONTES_BI...
           Travel                                    ZipcarZIPCAR_INCZIPCAR_INC
5.May      Bills & Utilities  AMZ_Sling_TV_L__L__CAMZ_Sling_TV_L__L__CAudibl...
           Entertainment                                HBOAMZ_The_Washington_P
           Food & Drink       CENTRAL_LIQUORSCENTRAL_LIQUORSCENTROLINACENTRO...
           Groceries          GW_DELICATESSENINSTACARTWHOLEFDSCAPT_WHITES_SE...
           MISC                                                          ELEVEN
           Personal                               CVSCVSWALGREENSAMZ_Fabric_com
           Shopping           AMZNAMZNAMZNAPPLE_COM_BILLAmazonIMPERIAL_WINE_...
6.June     Bills & Utilities  Yes_EnergyAMZ_Sling_TV_L__L__CAudibleSTARRY_IN...
           Entertainment                                HBOAMZ_The_Washington_P
           Food & Drink       LE_DIPLOMATEEYE_STREET_CELLARSJALEO_DCSUBWAYST...
           Groceries          SAFEWAYCAPT_WHITES_SEAFOOD_CITYWHOLEFDSWHOLEFD...
           MISC                                       PP_FACEBOOKPAY_AMERICANCA
           Personal                                   CVSBANGSALONVERIZONCENTER
           Shopping           AmazonAmazonAMZNAMZNAPPLE_COM_BILLAMZNAMZNSODA...
           Travel                                                        Zipcar
7.July     Bills & Utilities  AMZ_Sling_TV_L__L__CYes_EnergyAMZ_Sling_TV_L__...
           Education                                                 CODECADEMY
           Entertainment                                                    HBO
           Food & Drink       SOMTAM_HOLDINGS___LLCSTARBUCKSPENN_QUARTER_SPO...
           Groceries          HANA_GROCERY_STORETRADERINSTACARTWHOLEFDSSAFEW...
           MISC                                                          ELEVEN
           Personal                           WALGREENSWALGREENSCVSCVSWALGREENS
           Shopping           AMZNAmazonDISTRICT_CUTLERYAPPLE_COM_BILLPrimeA...
8.August   Bills & Utilities  STARRY_INTERNETPYL_Tilton_Bernstein_ManaEtsyTM...
           Food & Drink       MEXICUE___DCEYE_STREET_CELLARSFREE_STATEIN__TH...
           Groceries                SAFEWAYTRADERHANA_GROCERY_STOREGIANTSAFEWAY
           Personal                                  CVSWALGREENSLOGAN_HARDWARE
           Shopping                                                       Prime

                                     Amount
                             count      sum count
Month      Category
1.January  Bills & Utilities     3   570.50     3
           Entertainment         2    42.15     2
           Food & Drink         23  1320.14    23
           Groceries            19  1052.74    19
           MISC                  2    41.20     2
           Personal              6    95.23     6
           Shopping             14   581.33    14
           Travel               24   468.35    24
2.February Bills & Utilities     5   752.15     5
           Entertainment         1    15.89     1
           Food & Drink         12   597.31    12
           Groceries            20   931.57    20
           Personal              5    74.74     5
           Shopping             31  1373.97    31
           Travel               23   799.31    23
3.March    Bills & Utilities     7   837.79     7
           Entertainment         1    15.89     1
           Food & Drink         16   985.51    16
           Groceries            33  1770.85    33
           Personal              7   163.61     7
           Shopping             19   748.71    19
           Travel                9   137.96     9
4.April    Bills & Utilities     7   950.47     7
           Entertainment         1    15.89     1
           Food & Drink          8   244.60     8
           Groceries            28  1924.88    28
           Shopping             25   466.13    25
           Travel                3   135.32     3
5.May      Bills & Utilities     7  1156.41     7
           Entertainment         2    16.95     2
           Food & Drink         23   929.19    23
           Groceries            19  1318.82    19
           MISC                  1     2.99     1
           Personal              4   166.22     4
           Shopping             27   638.04    27
6.June     Bills & Utilities     7   835.67     7
           Entertainment         2    26.49     2
           Food & Drink         16  1349.98    16
           Groceries            20  1489.25    20
           MISC                  1    31.12     1
           Personal              2   120.23     2
           Shopping             37   912.26    37
           Travel                1    35.28     1
7.July     Bills & Utilities     9   829.11     9
           Education             1   239.88     1
           Entertainment         1    15.89     1
           Food & Drink         19  1173.45    19
           Groceries            17  1440.13    17
           MISC                  1    10.50     1
           Personal              5    60.36     5
           Shopping             18   528.39    18
8.August   Bills & Utilities     4   669.13     4
           Food & Drink          5   326.27     5
           Groceries             5   220.55     5
           Personal              3    79.15     3
           Shopping              1     7.41     1